# Generated by Django 3.2.7 on 2021-09-28 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('state', models.CharField(choices=[('P1', 'Proposed'), ('P2', 'Planned'), ('H1', 'Happening'), ('H2', 'Happened')], default='P1', max_length=2)),
                ('ranking', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('img', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('fullname', models.CharField(blank=True, max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('website', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Website')),
                ('rating', models.CharField(blank=True, max_length=40, null=True, verbose_name='Rating')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('photo_url', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Photo')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.friend')),
            ],
        ),
        migrations.CreateModel(
            name='FriendGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img_url', models.TextField(blank=True)),
                ('is_private', models.BooleanField(blank=True, default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='friendGroup',
            field=models.ManyToManyField(blank=True, to='core.FriendGroup'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='attender',
            field=models.ManyToManyField(blank=True, related_name='attending_set', to='core.Friend'),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.friend'),
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.friendgroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('editable_by', models.ManyToManyField(related_name='editable_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visible_for', models.ManyToManyField(related_name='visible_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
