# Generated by Django 3.2.7 on 2021-09-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
    ]
