# Generated by Django 3.2.7 on 2021-09-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='group',
        ),
    ]
