# Generated by Django 3.2.7 on 2021-09-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendgroup',
            name='img_url',
            field=models.TextField(blank=True),
        ),
    ]
