# Generated by Django 3.2.7 on 2021-10-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211003_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('P1', 'Proposed'), ('P2', 'Planned'), ('H1', 'Happening'), ('H2', 'Happened'), ('N', 'Not Happened')], default='P1', max_length=2),
        ),
    ]
