# Generated by Django 3.2.7 on 2021-09-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_friendgroup_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ranking',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('P1', 'Proposed'), ('P2', 'Planned'), ('H1', 'Happening'), ('H2', 'Happened')], default='P1', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
