# Generated by Django 3.2.7 on 2021-09-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friendGroup',
            field=models.ManyToManyField(blank=True, to='core.FriendGroup'),
        ),
    ]
