# Generated by Django 3.2.7 on 2021-09-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_friend_friendgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friendGroup',
            field=models.ManyToManyField(null=True, to='core.FriendGroup'),
        ),
    ]
