# Generated by Django 3.2.7 on 2021-10-06 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_badge_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgefriendrelationship',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='core.badge'),
        ),
    ]
