# Generated by Django 3.2.7 on 2021-10-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_badgefriendrelationship_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
