# Generated by Django 3.2.7 on 2021-10-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_badge_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='img',
            new_name='image_url',
        ),
    ]
