# Generated by Django 3.2.7 on 2021-09-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210915_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location_county',
        ),
        migrations.AddField(
            model_name='event',
            name='location_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_photo_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_website',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Website'),
        ),
    ]
