# Generated by Django 3.2.7 on 2021-09-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210915_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_photo_url',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_rating',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_website',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Website'),
        ),
    ]
