# Generated by Django 3.2.7 on 2021-10-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20211007_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='comments',
            field=models.ManyToManyField(related_name='_core_eventcomment_comments_+', to='core.EventComment'),
        ),
    ]
