# Generated by Django 3.2.7 on 2021-10-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_eventcomment_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='has_comments', to='core.EventComment'),
        ),
    ]
