# Generated by Django 3.2.7 on 2021-09-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210915_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_photo_url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_website',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Website'),
        ),
    ]
