# Generated by Django 3.2.7 on 2021-09-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210915_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
    ]
