# Generated by Django 3.2.7 on 2021-10-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_eventcomment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomment',
            name='is_inner_comment',
            field=models.BooleanField(default=False),
        ),
    ]
