# Generated by Django 3.2.7 on 2021-09-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_event_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
    ]
