# Generated by Django 3.2.7 on 2021-10-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_eventcomment_is_inner_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='has_comments', to='core.EventComment'),
        ),
    ]
