# Generated by Django 3.2.7 on 2021-10-07 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_eventcomment_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.BooleanField(default=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventcomment')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='core.friend')),
            ],
        ),
    ]
