# Generated by Django 3.2.7 on 2021-10-07 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_eventcommentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcommentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='core.eventcomment'),
        ),
        migrations.AlterField(
            model_name='eventcommentlike',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_comment_likes', to='core.friend'),
        ),
    ]
