# Generated by Django 3.2.7 on 2021-10-07 21:34

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20211007_2119'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventcommentlike',
            managers=[
                ('likes', django.db.models.manager.Manager()),
            ],
        ),
    ]
