# Generated by Django 3.2.7 on 2021-09-21 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_alter_friend_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attender',
            field=models.ManyToManyField(blank=True, related_name='attending_set', to='core.Friend'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
