# Generated by Django 3.2.7 on 2021-10-08 12:13

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20211008_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcommentlike',
            name='comment',
        ),
        migrations.AddField(
            model_name='event',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True, default=timezone.now()),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True, default=timezone.now()),
        ),
        migrations.AddField(
            model_name='friend',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True, default=timezone.now()),
        ),
        migrations.AddField(
            model_name='friendgroup',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True, default=timezone.now()),
        ),
        migrations.AddField(
            model_name='location',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True, default=timezone.now()),
        ),
        migrations.AddField(
            model_name='vote',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True, default=timezone.now()),
        ),
        migrations.AlterField(
            model_name='eventcommentlike',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='core.eventcomment'),
        ),
    ]
