# Generated by Django 3.2.7 on 2021-10-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20211008_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='friendgroup',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='is_active',
        ),
    ]
