# Generated by Django 3.2.7 on 2021-09-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_event_attender'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendgroup',
            name='is_private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
