# Generated by Django 3.2.7 on 2021-09-22 13:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_friendgroup_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='fullname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='friend',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
