# Generated by Django 3.2.7 on 2021-09-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_friend_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('website', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Website')),
                ('rating', models.CharField(blank=True, max_length=40, null=True, verbose_name='Rating')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('photo_url', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Photo')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_longitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_phone_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_photo_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_rating',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_website',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
    ]
