# Generated by Django 3.2.7 on 2021-10-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20211008_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='friendgroup',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='location',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='deleted',
        ),
    ]
