# Generated by Django 3.2.7 on 2021-10-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20211010_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendgroup',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
