# Generated by Django 3.2.7 on 2021-10-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20211010_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('E', 'Entertainment'), ('W', 'Work'), ('M', 'Meeting'), ('O', 'Outdoor'), ('V', 'Vacation'), ('S', 'Study')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(blank=True, choices=[('P1', 'Proposed'), ('P2', 'Planned'), ('H1', 'Happening'), ('H2', 'Happened'), ('N', 'Not Happened')], default='P1', max_length=2),
        ),
    ]
